# TODO add a custom docker file from gitpod/workspace-base to include openjdk:8-jdk
# otherwise the build and execution will occur on JDK 11
tasks:
  - before: chmod +x mvnw
  - init: ./mvnw install -DskipTests=true
