java ^
-Dlog.root.level=trace ^
-Dlogback.configurationFile=logback-test.xml ^
-Dpoll.timeout=15 ^
-Dpoll.delay=5 ^
-Dsaucelabs.reporter.url= ^
-Dprovider= ^
-Ddevice.type=windows ^
-Dbuild.label=STANDALONE ^
-Dbuild.tags= ^
-Dapplication.filename=Microsoft.WindowsCalculator_8wekyb3d8bbwe!App ^
-Dapplication.workingdir= ^
-Denvironment.label=default ^
-Dtest.properties.file=environments/default/test.properties ^
-Djgiven.report.dir=target/jgiven-reports ^
-Ddryrun= ^
-Dscreenshots= ^
-DscreenshotDelayMs=500 ^
-jar target/qa-testing-example-0.0.9-SNAPSHOT-test-with-dependencies.jar ^
-d target/test-output ^
testing-windows.xml
