volumes:
  maven-cache:

services:
  tests:
    image: mcr.microsoft.com/vscode/devcontainers/java:11
    user: vscode
    command: sleep infinity
    volumes:
      - maven-cache:/home/vscode/.m2

#  chrome:
#    image: selenium/node-chrome:4.21.0
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    ports:
#      - "7900:7900"
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - VNC_NO_PASSWORD=1
#
#  firefox:
#    image: selenium/node-firefox:4.21.0
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    ports:
#      - "7902:7900"
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - VNC_NO_PASSWORD=1
#
#  selenium-hub:
#    image: selenium/hub:4.21.0
#    ports:
#      - "4442:4442"
#      - "4443:4443"
#      - "4444:4444"
