name: generate automation and build

on:
  workflow_call:
    inputs:
      archetype-version:
        required: true
        type: string

jobs:

  generate-automation-project:
    name: ${{ matrix.os }} generate and test tutorials
    runs-on: ${{ matrix.os }}
    environment: development

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: setup maven for sonatype snapshots
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: >
            [
              {
                "id": "ossrh",
                "url": "https://s01.oss.sonatype.org/content/repositories/snapshots",
                "snapshots": {
                    "enabled": "true",
                    "checksumPolicy": "warn"
                }
              }
            ]

      # FIXME should run with controlled java version
      - name: bootstrap maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: setup maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: generate testing project
        shell: bash
        run: |
          mvn --batch-mode archetype:generate \
            -DarchetypeGroupId=dev.aherscu.qa \
            -DarchetypeArtifactId=qa-testing-archetype \
            -DarchetypeVersion=${{ inputs.archetype-version }} \
            -DgroupId=com.acme \
            -DartifactId=testing \
            -Dversion=1.0-SNAPSHOT \
            -Dpackage=com.acme.testing

      - name: build standalone testing project
        shell: bash
        run: |
          cd testing && chmod +x mvnw && ./mvnw package -Pmode-build-full,generate-standalone

      - name: run standalone testing project
        shell: bash
        env:
          SAUCELABS_USER: ${{ secrets.SAUCELABS_USER }}
          SAUCELABS_PASSWORD: ${{ secrets.SAUCELABS_PASSWORD }}
        run: |
          cd testing && chmod +x standalone-tutorials.sh && ./standalone-tutorials.sh
