name: matrix build

on:
  workflow_call:
    inputs:
      config-path:
        type: string

jobs:

  matrix-build:
    name: ${{ matrix.os }} jdk-${{ matrix.java-version }} build w/o tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # ISSUE on JDK 21 --
        #  when running aggregated as
        #  mvnw install mode-build-full mode-build-nosign testing-tutorials
        #  while running qa-testing-example:
        #  Cannot define class using reflection: Unable to make protected java.lang.Package
        #  when running verify on qa-testing-example standalone:
        #  java.lang.RuntimeException: ProcessBuilder.start() debug
        #  (in addition)
        #  In summary, on JDK 21 the tests do not work.
        java-version: [ 21, 17, 11 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
          settings-path: ${{ github.workspace }}

      - name: unix mvn install
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          chmod +x mvnw && ./mvnw install \
            -s $GITHUB_WORKSPACE/settings.xml

      - name: windows mvn install
        if: ${{ contains(matrix.os, 'windows') }}
        shell: cmd
        run: |
          mvnw install ^
            -s %GITHUB_WORKSPACE%\settings.xml
