name: nightly main branch build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # nightly

jobs:

  matrix-build:
    uses: ./.github/workflows/matrix-build.yml
    secrets: inherit

  generate-automation-project:
    uses: ./.github/workflows/generate-automation-project.yml
    secrets: inherit
    with:
      archetype-version: ${{ needs.matrix-build.outputs.version }}
    needs: matrix-build
