name: release and push to central
on:
  push:
    tags:
      - '*'
jobs:
  maven-central-deploy:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          settings-path: ${{ github.workspace }}
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - run: chmod +x mvnw
      - run: ./mvnw clean install -s $GITHUB_WORKSPACE/settings.xml -Pmode-build-quiet
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/**/target/*.jar"
#          token: ${{ secrets.GITHUB_TOKEN }}
      - run: chmod +x mvnw
      - run: ./mvnw clean deploy -s $GITHUB_WORKSPACE/settings.xml -Pmode-build-quiet
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
