# Standalone, manually triggered, GitHub Actions tests

name: self test

on:
  workflow_dispatch:

jobs:
  verify:
    name: verify
    # ISSUE ChromeDriver/GeckoDriver fail to initialize on Ubuntu
    # see https://github.com/QA-Automation-Starter/qa-automation/actions/runs/3294884059/jobs/5432863668
    # see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    # and https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          settings-path: ${{ github.workspace }}
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          version: '3.8.9'
          ports: '1883:5672 8883:15672'
          container-name: 'mqtt'

      - name: Maven verify
        run: |
          cd qa-testing-example && mvn verify
            -s $GITHUB_WORKSPACE/settings.xml \
            -Pmode-build-quiet,mode-build-fast,environment-dev,testing-tutorials

        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
