name: self test

on: [ workflow_dispatch ]

jobs:
  run-self-test:
    name: self test

    runs-on: windows-2022
    environment: development

    steps:
      - name: experiment
        shell: cmd
        run: |
          dir
